version: '3.3'
services:

  filebeat:
    image: filebeat:latest
    container_name: filebeat
    build:
          context: .
          dockerfile: filebeat/Dockerfile
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    volumes:
      - ./logs:/var/logs
    links:
      - logstash
    networks:
      - esnet

  logstash:
    image: logstash:latest
    container_name: logstash
    build:
          context: .
          dockerfile: logstash/Dockerfile
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - xpack.monitoring.elasticsearch.url=http://elasticsearch:9200
    ports:
      - 5044:5044
      - 9600:9600
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    expose:
      - 5044
      - 9600
    networks:
      - esnet

  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    build:
          context: .
          dockerfile: elasticsearch/Dockerfile
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    networks:
      - esnet

  elasticsearch2:
    image: elasticsearch2:latest
    container_name: elasticsearch2
    build:
          context: .
          dockerfile: elasticsearch/Dockerfile
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS="-Xms512m -Xmx512m"
      - discovery.zen.ping.unicast.hosts=elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: kibana:latest
    container_name: kibana
    build:
          context: .
          dockerfile: kibana/Dockerfile
    environment:
      - server.name=kibana
      - server.host="0"
      - elasticsearch.url=http://elasticsearch:9200
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    expose:
      - 5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
    external: true
